import { Album, Song } from "../../things";
import { Wintersun } from "../../artists";

export const albumTimeII: Album = {
  title: "Time II",
  artist: Wintersun,
  wiki: new URL("https://en.wikipedia.org/wiki/Time_II"),
  year: 2024,
  src: { spotify: "27TYlqOWbO1zClQVHfTjOt" },
};

export default albumTimeII;

export const songFieldsOfSnow: Song = {
  release: albumTimeII,
  title: "Fields of Snow",
  src: { youtube: "3kXHkFW4jd8", spotify: "3bpoS0oqf1UQrfRDrkHiwM" },
  qualities: {
    jari: 3,
    black: 0,
    death: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    choirs: 2,
    singalong: 0,
    riffs: 1,
    solos: 3,
    melodic: 3,
    energetic: 2,
    epic: 3,
    folk: 2,
    intense: 1,
    melancholic: 2,
  },
};

export const songTheWayOfTheFire: Song = {
  release: albumTimeII,
  title: "The Way of the Fire",
  src: { youtube: "4l5TfUESbNA", spotify: "6a3fzQf9SbrbkBZtbUWVEG" },
  qualities: {
    jari: 3,
    black: 2,
    death: 1,
    power: 3,
    thrash: 1,
    clean: 2,
    extreme: 3,
    choirs: 1,
    singalong: 3,
    riffs: 2,
    solos: 3,
    melodic: 3,
    energetic: 3,
    epic: 3,
    folk: 1,
    intense: 2,
    melancholic: 1,
  },
};

export const songOneWithTheShadows: Song = {
  release: albumTimeII,
  title: "One With the Shadows",
  src: { youtube: "41XpPUrnWMc", spotify: "3V5K9mzaGEQZILvsWk9n3z" },
  qualities: {
    jari: 3,
    black: 2,
    death: 0,
    power: 0,
    thrash: 1,
    clean: 2,
    extreme: 3,
    choirs: 2,
    singalong: 3,
    riffs: 2,
    solos: 3,
    melodic: 3,
    energetic: 1,
    epic: 3,
    folk: 2,
    intense: 2,
    melancholic: 3,
  },
};

export const songOminousClouds: Song = {
  release: albumTimeII,
  title: "OminousClouds",
  src: { youtube: "aB1WPakAuyA", spotify: "2fR0Hh4hg64gcFwdfH1VbA" },
  qualities: {
    jari: 3,
    black: 0,
    death: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    choirs: 0,
    singalong: 0,
    riffs: 0,
    solos: 3,
    melodic: 3,
    energetic: 1,
    epic: 1,
    folk: 0,
    intense: 0,
    melancholic: 2,
  },
};

export const songStorm: Song = {
  release: albumTimeII,
  title: "Storm",
  src: { youtube: "5rk6b5GdX_4", spotify: "2ds59iDerMahxHhboiXjQm" },
  qualities: {
    jari: 3,
    black: 3,
    death: 1,
    power: 1,
    thrash: 3,
    clean: 2,
    extreme: 3,
    choirs: 2,
    singalong: 2,
    riffs: 3,
    solos: 3,
    melodic: 3,
    energetic: 3,
    epic: 3,
    folk: 2,
    intense: 3,
    melancholic: 3,
  },
};

export const songSilverLeaves: Song = {
  release: albumTimeII,
  title: "Silver Leaves",
  src: { youtube: "7mCSNGOG3GM", spotify: "5tgR5YDgY9rbAw5w9lLhOo" },
  qualities: {
    jari: 3,
    black: 0,
    death: 0,
    power: 1,
    thrash: 1,
    clean: 3,
    extreme: 0,
    choirs: 2,
    singalong: 3,
    riffs: 1,
    solos: 1,
    melodic: 3,
    energetic: 1,
    epic: 2,
    folk: 3,
    intense: 1,
    melancholic: 2,
  },
};
