import { Album, Song } from "../../things";
import { albumWintersunTimeI } from "./albumTimeI";

export const albumWintersunTimeIInstrumental: Album = {
  title: albumWintersunTimeI.title + " (Instrumental)",
  artist: albumWintersunTimeI.artist,
  wiki: albumWintersunTimeI.wiki,
  year: albumWintersunTimeI.year,
  src: {},
};

export const songWhenTimeFadesAway: Song = {
  release: albumWintersunTimeIInstrumental,
  title: "When Time Fades Away",
  src: { youtube: "1Sc1LIYlzuQ" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songSonsOfWinterAndStars: Song = {
  release: albumWintersunTimeIInstrumental,
  title: "Sons of Winter and Stars (Instrumental)",
  src: { youtube: "1Sc1LIYlzuQ&start=257" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songLandOfSnowAndSorrow: Song = {
  release: albumWintersunTimeIInstrumental,
  title: "Land of Snow and Sorrow (Instrumental)",
  src: { youtube: "k1WqOsBRTwo" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songDarknessAndFrost: Song = {
  release: albumWintersunTimeIInstrumental,
  title: "Darkness and Frost",
  src: { youtube: "68B3fhunbsU" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songTime: Song = {
  release: albumWintersunTimeIInstrumental,
  title: "Time",
  src: { youtube: "68B3fhunbsU&start=147" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};
