import { Album, Song } from "../../things";
import { Ensiferum } from "../../artists";

export const albumEnsiferum: Album = {
  title: "Ensiferum",
  artist: Ensiferum,
  year: 2001,
  wiki: new URL("https://en.wikipedia.org/wiki/Ensiferum_(album)"),
  src: { spotify: "1UrdsJhCNyCqmBn9zy2Ut9" },
};

export default albumEnsiferum;

export const songIntro: Song = {
  release: albumEnsiferum,
  title: "Intro",
  src: { youtube: "rL3e4LH236w", spotify: "45LbKMd573GvriZR60E7DG" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songHeroInADream: Song = {
  release: albumEnsiferum,
  title: "Hero in a Dream",
  src: { youtube: "Es8VIH-UH2w", spotify: "1ERKFXkhj7UekblpgUw2fF" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songTokenOfTime: Song = {
  release: albumEnsiferum,
  title: "Token of Time",
  src: { youtube: "BGpb1vv8hjo", spotify: "6NlRFM6YPUDQLTL94Cyf7W" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songGuardiansOfFate: Song = {
  release: albumEnsiferum,
  title: "Guardians of Fate",
  src: { youtube: "1XlvSPTzKZo", spotify: "6vXlfcORbavPtxIPYGYYbz" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songOldMan: Song = {
  release: albumEnsiferum,
  title: "Old Man (Väinämöinen)",
  src: { youtube: "uxrbG1oIi0E", spotify: "1IoBqiz40yvzhZnTnQt6bT" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songLittleDreamer: Song = {
  release: albumEnsiferum,
  title: "Little Dreamer (Väinämöinen Part II)",
  src: { youtube: "ILUaqsC0ulI", spotify: "49sHjT9q3WsuwhLJ3G5LEy" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songAbandoned: Song = {
  release: albumEnsiferum,
  title: "Abandoned",
  src: { youtube: "rd_hJ3tVfAY", spotify: "1bXjgN41CumYbZovb0KAzn" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songWindrider: Song = {
  release: albumEnsiferum,
  title: "Windrider",
  src: { youtube: "UlUD_X3lGY4", spotify: "6xtjbKMvK69gjhhcdBRuwB" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songTreacherousGods: Song = {
  release: albumEnsiferum,
  title: "Treacherous Gods",
  src: { youtube: "1HphiKoduC8", spotify: "0SAXvT9zZx4B36Eu3TwVYs" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songEternalWait: Song = {
  release: albumEnsiferum,
  title: "Eternal Wait",
  src: { youtube: "WbBMh-ZvnkA", spotify: "2qUU8a2ovr5AMifrzrPrZS" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songBattleSong: Song = {
  release: albumEnsiferum,
  title: "Battle Song",
  src: { youtube: "DGwE1KGf2dY", spotify: "1RAePnGQvZn6dQxt05OISI" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songGoblinsDance: Song = {
  release: albumEnsiferum,
  title: "Goblin's Dance",
  src: { youtube: "P8zUj6yhDM0", spotify: "2OBXIrRkIIRZXkXZBRFOiF" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};
