import { Album, Song } from "../../things";
import { Ensiferum } from "../../artists";

export const albumIron: Album = {
  title: "Iron",
  artist: Ensiferum,
  year: 2004,
  wiki: new URL("https://en.wikipedia.org/wiki/Iron_(Ensiferum_album)"),
  src: { spotify: "1UrdsJhCNyCqmBn9zy2Ut9" },
};

export default albumIron;

export const songFerrumAeternum: Song = {
  release: albumIron,
  title: "Ferrum Aeternum",
  src: { youtube: "AvCDRK13yv8", spotify: "3SdUwF3swZgYCBRDIAsf0c" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songIron: Song = {
  release: albumIron,
  title: "Iron",
  src: { youtube: "IYq4AePD72M", spotify: "0wwAkc9n9SfV27COAK2AUH" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songSwordChant: Song = {
  release: albumIron,
  title: "Sword Chant",
  src: { youtube: "3RkuvOaReiA", spotify: "7sYXsljeNiPXZVjXb5HuKX" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songMourningHeartInterlude: Song = {
  release: albumIron,
  title: "Mourning Heart - Interlude",
  src: { youtube: "Nf0F0dAlm0Q", spotify: "2Hf2byNwWzrxoMAK4GBfHV" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songTaleOfRevenge: Song = {
  release: albumIron,
  title: "Tale of Revenge",
  src: { youtube: "uVhq9UyDzEk", spotify: "5T8tc2aeIRxtjhUu762WJP" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songLostInDespair: Song = {
  release: albumIron,
  title: "Lost in Despair",
  src: { youtube: "Gj7sG0zPuQk", spotify: "3jZTEN6W2m9rESBhayO33M" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songSlayerOfLight: Song = {
  release: albumIron,
  title: "Slayer of Light",
  src: { youtube: "m4URBdnwet4", spotify: "0XATQ6wedL4bMP2emZNE9F" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songIntoBattle: Song = {
  release: albumIron,
  title: "Into Battle",
  src: { youtube: "A_r7GhkeFWw", spotify: "5XRUjUcadB3qBVgmp1cJ0e" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songLaiLaiHei: Song = {
  release: albumIron,
  title: "Lai Lai Hei",
  src: { youtube: "eMXGruO8zBU", spotify: "1Mp05e1nlnPnuZLnvJKuSy" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songTears: Song = {
  release: albumIron,
  title: "Tears",
  src: { youtube: "ZulDLr1oTYs", spotify: "6GqkpIizS6DMfcCKDji0qy" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};

export const songBattery: Song = {
  release: albumIron,
  title: "Battery",
  src: { youtube: "kwzwWl12NYs", spotify: "0EiiHEl43VwwemR4Gcrnkw" },
  qualities: {
    jari: 0,
    black: 0,
    death: 0,
    folk: 0,
    power: 0,
    thrash: 0,
    clean: 0,
    extreme: 0,
    singalong: 0,
    melodic: 0,
    riffs: 0,
    solos: 0,
    energetic: 0,
    epic: 0,
    intense: 0,
    melancholic: 0,
  },
};
