name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
    type: [opened]
  workflow_dispatch:

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    name: Deploy artifact to GH pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        timeout: "60000" # One minute
