name: Deploy to GitHub Pages

on:
  push:

jobs:
  deploy:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install npm dependencies
        run: npm install

      - name: Build for production
        run: npm run build
